"""first

Revision ID: 17eb6c6b43b3
Revises: 
Create Date: 2023-02-18 07:51:41.098191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17eb6c6b43b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breads_name'), 'breads', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breads_name'), table_name='breads')
    op.drop_table('breads')
    # ### end Alembic commands ###
