name: FastAPI ci-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env: 
          MYSQL_DATABASE: tests
          MYSQL_ROOT_PASSWORD: secret 
        ports:
          - 3307:3306

    steps:
      - name: Load Mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 --port 3307 -u rppt -psecret -e 'CREATE DATABASE IF NOT EXISTS tests;'


      
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Running Tests
        run: python -m pytest