name: FastAPI ci-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env: 
          MYSQL_DATABASE: tests
          MYSQL_ROOT_PASSWORD: secret 
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.12'

      - name: Load Mysql
        run: |
          mysql -h 127.0.0.1 --port 3307 -u root -psecret -e 'CREATE DATABASE IF NOT EXISTS tests;'
      
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Running Tests
        run: python -m pytest