Stack Overflow
Products
Search…
ericolvr's user avatar
ericolvr
99, 99 reputation
●22 silver badges●1111 bronze badges
2
Home
PUBLIC
Questions
Tags
Users
Companies
COLLECTIVES
Explore Collectives
TEAMS
Create free Team
Github action with MySQL test database
Asked 2 years ago
Modified 1 year, 4 months ago
Viewed 5k times

Report this ad

3


I have a CodeIgniter Web app connected with Mysql that is developed in the docker. I would like to do some unit test in the GitHub action fo ci/cd pipeline. The problem is some of the function would require enquiry data from Mysql database. So may I know if there is a way to setup a MySQL instance on Github action and run some .sql file so that my test data is in the database?

mysqldockergithubcontinuous-integration
Share
Edit
Follow
Flag
edited Jan 27, 2021 at 7:05
Deepak Rai's user avatar
Deepak Rai
2,12333 gold badges2121 silver badges3535 bronze badges
asked Jan 27, 2021 at 7:01
sfsf9797's user avatar
sfsf9797
45444 silver badges1212 bronze badges
Add a comment
Start a bounty
2 Answers
Sorted by:

Highest score (default)

1


You can use GitHub Actions service containers to connect to databases like mysql. You can find details at https://docs.github.com/en/actions/guides/about-service-containers

Share
Edit
Follow
Flag
answered Jan 27, 2021 at 14:49
Rajesh Goyal's user avatar
Rajesh Goyal
11911 silver badge66 bronze badges
Add a comment

Report this ad

1


I think this script can help people to conduct unit test with MySQL database and a .sql script file to load table schema and data on Github action. I am using Codeigniter 4 with Mysql. But the process of setting up a database would be similar as long as you are using MySQL.

name:  CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build

    - name: up mysql and apache container runs
      run: docker-compose up -d

     #I am using codeIgniter4
    - name: install dependencies
      run: docker exec  CI4_1 php composer.phar install

    - name: buffering time for db container
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    #db_1 is the name of database
    - name: load database
      run: docker exec -i mysql_1  mysql -uroot  -proot  db_1< ./testDatabase.sql

   

    - name: unit test
      run: docker exec  CI4_1  ./vendor/bin/phpunit
Share
Edit
Follow
Flag
answered Oct 10, 2021 at 4:46
sfsf9797's user avatar
sfsf9797
45444 silver badges1212 bronze badges
1

Are there advantages or disadvantages when running a container directly in a step vs using github's "service containers"? – 
evgeni tsvetanov
 Jan 17, 2022 at 14:12
Add a comment
Your Answer


Community wiki
Not the answer you're looking for? Browse other questions tagged mysqldockergithubcontinuous-integration or ask your own question.
The Overflow Blog
Monitoring debt builds up faster than software teams can pay it off
Because the only thing worse than building internal tools is maintaining them...
Featured on Meta
Ticket smash for [status-review] tag: Part Deux
We've added a "Necessary cookies only" option to the cookie consent popup
We’ve made changes to our Privacy Notice for Collectives™
The [amazon] tag is being burninated
Microsoft Azure Collective launch and proposed tag changes
Temporary policy: ChatGPT is banned

Report this ad
19 people chatting
SQL
Feb 13 at 6:47 - WhatsThePoint
WhatsThePoint: Feb 13 at 6:47
Related
1261
How do I connect to a MySQL Database in Python?
3097
Should I use the datetime or timestamp data type in MySQL?
577
How to shrink/purge ibdata1 file in MySQL
1777
Download a single folder or directory from a GitHub repo
4564
How do I update or sync a forked repository on GitHub?
1323
GitHub relative link in Markdown file
3073
How to add images to README.md on GitHub?
2659
How do I import an SQL file using the command line in MySQL?
1400
Create a tag in a GitHub repository
Hot Network Questions
AC coupling to center an oscillating waveform to 0V doesn't work
What is the Statistical Method?
Photos of people in airplanes specifically not permitted
In Kerouac's On The Road, what is snakejuice?
Is there a word or phrase that describes the retention of a result in a sport game?
Can a Beguiler benefit from Greyhawk Method?
Best way to connect wires to PCB
Supervisor taking first authorship after student has left university
Is it possible to execute certain commands after bibliography is ended?
Why does Jesus seemingly contradict what He states in Mt 5:19 by later appearing to relax the Law of the Sabbath?
more hot questions
 Question feed

STACK OVERFLOW
Questions
Help
PRODUCTS
Teams
Advertising
Collectives
Talent
COMPANY
About
Press
Work Here
Legal
Privacy Policy
Terms of Service
Contact Us
Cookie Settings
Cookie Policy
STACK EXCHANGE NETWORK
Technology
Culture & recreation
Life & arts
Science
Professional
Business
API
Data
Blog
Facebook
Twitter
LinkedIn
Instagram
Site design / logo © 2023 Stack Exchange Inc; user contributions licensed under CC BY-SA. rev 2023.2.17.43248